const mongoose = require('mongoose')
const Schema = mongoose.Schema

const unidadesClientesSchema = new Schema({
    idUnidad: Number,
	idUnidadID: String,
	contadorBytes: Number,
	paroMotor: Boolean,
	alertPanico: Boolean,
	ultimaFechaConexion: Date,
	fechaUltEnvioParoMotor: Date,
	fechaUltAlertaPanico: Date,
	esperaSmsParoMotor: Boolean,
	fechaUltEnvioSmsParoMotor: Date,
	fechaUltEvento: Date,
	modeloEquipoTrama: String,
	horariosCorteRuta: String,
	marcaUnidad: String,
	modeloUnidad: String,
	anioUnidad: String,
	colorUnidad: String,
	numSerieUnidad: String,
	numSerieMotor: String,
	numEconomico: String,
	simCardNumTele: String,
	ladaTelefono: String,
	tipoPlan: Number,
	fechaAlta: Date,
	SSP_ID: String,
	SSP_token: String,
	placasUnidad: String,
	clvSegPublica: String,
	metrosActualKilome: Number,
	seguimientoSSP: Boolean,
	ultAvisoEquipoDesconec: Date,
	estadoUnidad: Boolean,
	fechaUltAvisoJammer: Date,
	fechaUltAvisoDescBateria: Date,
	habilitarSmsPanico: Boolean,
	habilitarSmsParoMotor: Boolean,
	habilitarSmsJammerDetectado: Boolean,
	habilitarSmsBateriaDesconectada: Boolean,
	habilitarSmsInOutPuntoInteres: Boolean,
	habilitarSmsInOutSalidaGeocerca: Boolean,
	marcaEquipo: Number,
	inputUno: String,
	inputDos: String,
	inputTres: String,
	inputCuantro: String,
	inputCinco: String,
	inputSeis: String,
	inputSiente: String,
	inputOcho: String,
	outputUno: String,
	outputDos: String,
	outputTres: String,
	outputCuatro: String,
	outputCinco: String,
	outputSeis: String,
	outputSiete: String,
	outputOcho: String,
	vehiculoBloqueado: Boolean,
	contadorLitrosConsumidos: Number,
	none: String,
    idCliente: Number,
    nombreCliente: String,
    rfcCliente: String,
    idConductorAsignado: Number,
    idDomicilioUnidad: Number,
    idModelo: Number,
    idUsuarioActivoParoMotor: Number,
	idUsuarioActivoPanico: Number,
    idRegion: Number,
},{
    timestamps: true,
    versionKey: false,
});

const databaseB = mongoose.connection.useDb(process.env.DB_NAME_B)
const unidadesRelacionClientes = databaseB.model('unidadesRelacionClientes', unidadesClientesSchema)
module.exports = unidadesRelacionClientes