const mongoose = require('mongoose')
const Schema = mongoose.Schema

const unidadesSchema = new Schema({
    idUnidad: Number,
	idUnidadID: String,
	contadorBytes: Number,
	paroMotor: Boolean,
	alertPanico: Boolean,
	ultimaFechaConexion: Date,
	fechaUltEnvioParoMotor: Date,
	fechaUltAlertaPanico: Date,
	esperaSmsParoMotor: Boolean,
	fechaUltEnvioSmsParoMotor: Date,
	idCliente: Number,
	fechaUltEvento: Date,
	modeloEquipoTrama: String,
	horariosCorteRuta: String,
	marcaUnidad: String,
	modeloUnidad: String,
	anioUnidad: String,
	colorUnidad: String,
	numSerieUnidad: String,
	numSerieMotor: String,
	numEconomico: String,
	simCardNumTele: String,
	ladaTelefono: String,
	tipoPlan: Number,
	fechaAlta: Date,
	SSP_ID: String,
	SSP_token: String,
	idConductorAsignado: Number,
	idDomicilioUnidad: Number,
	idModelo: Number,
	placasUnidad: String,
	clvSegPublica: String,
	metrosActualKilome: Number,
	seguimientoSSP: Boolean,
	idUsuarioActivoParoMotor: Number,
	idUsuarioActivoPanico: Number,
	ultAvisoEquipoDesconec: Date,
	estadoUnidad: Boolean,
	idRegion: Number,
	fechaUltAvisoJammer: Date,
	fechaUltAvisoDescBateria: Date,
	habilitarSmsPanico: Boolean,
	habilitarSmsParoMotor: Boolean,
	habilitarSmsJammerDetectado: Boolean,
	habilitarSmsBateriaDesconectada: Boolean,
	habilitarSmsInOutPuntoInteres: Boolean,
	habilitarSmsInOutSalidaGeocerca: Boolean,
	marcaEquipo: Number,
	inputUno: String,
	inputDos: String,
	inputTres: String,
	inputCuantro: String,
	inputCinco: String,
	inputSeis: String,
	inputSiente: String,
	inputOcho: String,
	outputUno: String,
	outputDos: String,
	outputTres: String,
	outputCuatro: String,
	outputCinco: String,
	outputSeis: String,
	outputSiete: String,
	outputOcho: String,
	vehiculoBloqueado: Boolean,
	contadorLitrosConsumidos: Number,
	none: String,
},
{
    timestamps: true,
    versionKey: false,
});

const databaseB = mongoose.connection.useDb(process.env.DB_NAME_B)
const unidades = databaseB.model('unidades', unidadesSchema)
module.exports = unidades